# Generated by Django 3.0.4 on 2020-05-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200520_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(db_constraint=False, null=True, related_name='books', to='api.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='api.Publish'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
